version: '3.8'
services:
  song_app:
    build: 
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL}
    volumes:
      - .:/test_pro/src/app
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
